### ISSUE TITLE
Fix specs due to `isodoc` gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-vsd#3]
One spec now fails caused by the `isodoc` gem (https://github.com/metanorma/isodoc/issues/94).

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-vsd/pull/2#issuecomment-487818684_

**Comment by opoudjis** [comment]
I don't know why you're working on this gem at all, but that issue with isodoc has been resolved.
