### ISSUE TITLE
Migrate this gem to something more sustainable

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-vsd#4]
It is unsustainable to proliferate gems like this: we simply cannot continue to maintain them, and this gem in particular has been out of the maintenance loop for months. This gem should, if at all possible, become a skin of the generic metanorma-acme gem, which is being maintained.

**Comment by ronaldtse** [comment]
Agree. This gem should be a skin of Acme. It will be worthwhile to do this which allows us to make customization thinner for enterprise gems or for smaller SDOs (and therefore more scalable).

**Comment by opoudjis** [comment]
This is a priority to assign to someone new to the stack, since gem skinning is explicitly documented. I don't see any behaviour at all specific to VSD (the keywords under https://github.com/metanorma/metanorma-vsd/blob/master/lib/isodoc/vsd/metadata.rb are now redundant).

@skalee or @zoras, if you're looking for a project to get familiar with the stack with, this is a good one.

@ronaldtse The VSD customer would presumably need to be informed about the change.

**Comment by opoudjis** [comment]
Congratulations,@skalee, you're doing this.

The task is to take the existing metanorma-vsd gem (a Gem about which I know nothing), and to convert it into an instance of metanorma-acme: a Gem that takes CSS and HTML templates as arguments for any customisation (currently: as document header attributes of any input documents), as opposed to changing any code in the gem proper.

The result will be to get rid of metanorma-vsd as a distinct gem, and alleviate our maintenance burden. All the code needed to get VSD behaviour should be contained in metanorma-acme; it should just be configurable through external files (CSS and HTML). 

https://www.metanorma.com/builder/howto/adopting-toolchain/ is about creating new gems in general, but the intent here is that you don't need to create a new gem at all. To that end, you will likely need to create config files in metanorma-acme, that the VSD instance can use. In particular, a config file for the org name and namespace, which is currently contained in https://github.com/metanorma/metanorma-acme/blob/master/lib/metanorma/acme.rb

Consult https://www.metanorma.com/author/ref/document-attributes/ for the Asciidoctor document attributes that would be used to customise output of the metanorma-acme gem to match VSD: in particular, :i18nyaml:, and the "Visual appearance" group of attributes.

Eventually we would like to apply the same customisation to other gems, notably metanorma-rsd, potentially metanorma-csd, metanorma-csand, metanorma-m3d

I'm not sure whether this task makes sense to you; please contact me for clarification if not. It will serve as an introduction to how the stack works, and @ronaldtse thinks you will find plenty of things along the way to refactor...

**Comment by skalee** [comment]
Sounds great!

**Comment by ronaldtse** [comment]
Let me clarify. What we want is to generalize the acme gem to support VSD and some others. The key point is to NOT expose any template or css to the user.

**Comment by ronaldtse** [comment]
@opoudjis I don’t think the right solution is to put VSD and other enterprise flavors inside the metanorma-acme gem. That’s just wrong. Remember the enterprises are supposed to be able to customize their own templates. Instead, try to streamline the metanorma-vsd gem (ie based on acme) and make it into a gem like “mn-style-vsd” or something like that; something the user can easily customize. And MN should be able to load these style/layout gems automatically.

**Comment by opoudjis** [comment]
...

I want to see this activity result in the removal of metanorma-vsd and metanorma-rsd as distinct gems, which need to be tested and maintained separately, even though their code is the same, and they differ only in rendering and organisation names.

The entire point of this exercise is to cut down on the number of gems we need to maintain. If a single gem cannot be applied to all flavours of Metanorma that deviate minimally from metanorma-acme, then there is no point to it.

I'll add that a gem like mn-style-vsd is not something that a low-tech enterprise can maintain to begin with. The configuration specific to each enterprise should be *a single config file*.

So, @skalee.

There is information that right now is treated as document attributes of documents under the metanorma-acme gem (e.g. htmlstylesheet). There is also information that right now is treated as constants in lib/metanorma/acme.rb.

To comply with Ronald's requirements, I would prefer these attributes to be extracted into a local config file, that different enterprise users of the metanorma-acme gem can customise to point to different stylesheets and HTML files and org names.

Ultimately, you and Ronald can work out how you want to realise this. @ronaldtse if you want this to look different, you discuss it with Sebastian. But any solution that involves me maintaining a distinct gem for VSD and for RSD is a fail.

**Comment by opoudjis** [comment]
Ok, had a discussion with Ronald. This is the plan. I am only incompletely explaining it, because I don't understand the whole stack.

At the moment, there are template repositories in place for some flavours of Metanorma. The metanorma-cli executable understands how to talk to these template repositories. Somehow, and I am not interested in finding out how. You will need to.

Certain attributes used for styling of flavours of Metanorma will be stored on skinning repositories on github. Metanorma-cli will be able to interact with the skinning repository for the nominated flavour, and obtain the correct values for those skinning attributes. (And indeed the files themselves.)

You will note that the following document attributes contain rendering information, nominating local files: 

* :i18nyaml:
* :htmlstylesheet:
* :htmlcoverpage: 
* :htmlintropage:
* :scripts:
*  :scripts-pdf:
* :wordstylesheet:
* :standardstylesheet:
* :header:
* :wordcoverpage:
* :wordintropage:

These files in VSD currently live in the lib/isodoc/html directory. The metanorma-acme document assumes they will be loaded in as asciidoctor document attributes.

When you obtain those attribute values from the Metanorma skinning repository, somehow, and you download those files to an accessible local directory, somehow, you will need to manipulate the input asciidoctor document, to inject those document attribute values into the Asciidoctor document to be processed.

This is already being done in metanorma gem, lib/compile.rb, process_input():

````
file = File.read(filename, encoding: "utf-8")
        options[:asciimath] and
          file.sub!(/^(=[^\n]+\n)/, "\\1:mn-keep-asciimath:\n")
````

That code is injecting the document attribute mn-keep-asciimath into the document, if the processor was invoked with the asciimath option.


In addition to these attributes, the skinning repository will contain font names:

* :body-font:
* :header-font:
* :monospace-font:

And it will (eventually) contain organisation names, which currently are hardcoded in Acme. They will be populated into the Asciidoctor source in the same way, except they will not be file references.

metanorma-acme is intentionally a skeletal gem. Your job is to make it a shell for this kind of parameterised styling of Metanorma, and to implement skinning repositories, so that at minimum VSD and RSD gems are replaced with metanorma-acme (or whatever) plus the skinning repository attributes and files.

... @ronaldtse will be able to explain more. Please contact me if you have questions.

**Comment by w00lf** [comment]
@opoudjis @ronaldtse can i close this issue?

**Comment by ronaldtse** [comment]
@w00lf Is it possible to represent this gem just using configuration files? Thanks.

**Comment by w00lf** [comment]
> @w00lf Is it possible to represent this gem just using configuration files? Thanks.

@ronaldtse i will test if its possible now

**Comment by opoudjis** [comment]
This gem is exclusively config files and some initialisation code that I don't think can be avoided. (That's not going to be the case with RSD any more.)
